API RestAssured Homework
gibbonsite/TAF_AQA18_onl pull request #14
Opened 2023-02-11 13:28 UTC by gibbonsite

API RestAssured Homework is ready for checking.

2023-02-15 22:16 UTC, wildpioneer requested changes

2023-02-15 22:16 UTC, wildpioneer commented on src/test/java/tests/api/MilestonesTest.java
> +        int projectId = 1;
В общем и целом все хорошо, но мне очень не нравиться здесь жесткий ID проекта, соответственно:
Подумай, как обойти это жесткое задание ID

2023-02-19 12:19 UTC, gibbonsite commented on src/test/java/tests/api/MilestonesTest.java
> +        int projectId = 1;
Исправлено.

2023-02-28 10:08 UTC, wildpioneer commented
Проверено

2023-02-28 10:08 UTC, closed without merging