Selenium locators homework
gibbonsite/TAF_AQA18_onl pull request #2
Opened 2022-12-07 17:39 UTC by gibbonsite

Selenium locators homework is ready for checking.

2022-12-13 11:31 UTC, wildpioneer requested changes

2022-12-13 11:31 UTC, wildpioneer commented on src/test/java/tests/LaminateCalculatorTest.java
> +        laminateDirection1.click();
у меня здесь падает тест

2022-12-14 14:31 UTC, gibbonsite commented on src/test/java/tests/LaminateCalculatorTest.java
> +        laminateDirection1.click();
Добавил Thread.sleep(10) как мы обсуждали на занятии. Тест проходит: скриншот см. ниже.
![Laminate_test_passed](https://user-images.githubusercontent.com/219250/207622553-aa208817-7e6e-41e7-8a32-2ffd1cf085b5.png)

2022-12-20 09:21 UTC, wildpioneer commented
Проверено

2022-12-20 09:21 UTC, closed without merging