PageObject homework
gibbonsite/TAF_AQA18_onl pull request #5
Opened 2022-12-14 21:29 UTC by gibbonsite

PageObject homework is ready for checking.

2022-12-20 12:24 UTC, wildpioneer requested changes

2022-12-20 12:24 UTC, wildpioneer commented on src/test/java/pages/CheckoutCompletePage.java
> +public class CheckoutCompletePage extends BasePage {
У тебя ест 3 checkout страницы - в таком случае их надо перенести в отдельную папку

2022-12-20 12:24 UTC, wildpioneer commented on src/test/java/tests/CheckoutTest.java
> +        Assert.assertTrue(cartPage.isPageOpened());
Один тест - одна существенная проверка. У тебя же получается ты проверяешь все подряд.

2023-01-05 19:26 UTC, gibbonsite commented on src/test/java/pages/CheckoutCompletePage.java
> +public class CheckoutCompletePage extends BasePage {
Перенёс checkout страницы в отдельную папку.

2023-01-05 19:27 UTC, gibbonsite commented on src/test/java/tests/CheckoutTest.java
> +        Assert.assertTrue(cartPage.isPageOpened());
Исправил - теперь в одном тесте одна проверка.

2023-01-16 19:25 UTC, wildpioneer commented
Проверены изменения

2023-01-16 19:25 UTC, closed without merging