Advanced Selenium, wrappers homework
gibbonsite/TAF_AQA18_onl pull request #7
Opened 2023-01-11 17:42 UTC by gibbonsite

Wrappers homework is ready for checking.

2023-01-16 19:36 UTC, wildpioneer requested changes

2023-01-16 19:36 UTC, wildpioneer commented on src/test/java/elements/CheckBox.java
> +public class CheckBox {
Практически идеальная обертка, кроме комментария для метода click

2023-01-16 19:36 UTC, wildpioneer commented on src/test/java/elements/CheckBox.java
> +        if (flag != uiElement.isSelected()) {
Последний штрих - это здесь использовать isSelected() метод вместо uiElement.isSelected()

2023-01-16 19:36 UTC, wildpioneer commented on src/test/java/elements/DropDownMenu.java
> +    public void dropDown() {
Что делает этот метод? Я не смог понять по названию. Да и по реализации только догадываюсь

2023-01-16 19:36 UTC, wildpioneer commented on src/test/java/elements/DropDownMenu.java
> +        menuElementList.get(menuList.indexOf(text)).click();
А если я по незнанию вызову этот метод сразу после инициализации DropDown - получу exception ;)

2023-01-16 20:19 UTC, gibbonsite commented on src/test/java/elements/DropDownMenu.java
> +        menuElementList.get(menuList.indexOf(text)).click();
Исправил.

2023-01-16 20:19 UTC, gibbonsite commented on src/test/java/elements/DropDownMenu.java
> +    public void dropDown() {
Переименовал в showMenu.

2023-01-16 20:21 UTC, gibbonsite commented on src/test/java/elements/CheckBox.java
> +        if (flag != uiElement.isSelected()) {
Исправил.

2023-01-23 19:38 UTC, wildpioneer commented
Проверено

2023-01-23 19:38 UTC, closed without merging