Page Factory, Chain of Invocations, Value Object and Builder homework
gibbonsite/TAF_AQA18_onl pull request #8
Opened 2023-01-19 22:59 UTC by gibbonsite

Page Factory, Chain of Invocations, Value Object and Builder homework is ready for checking.

2023-01-23 19:36 UTC, wildpioneer requested changes

2023-01-23 19:36 UTC, wildpioneer commented on src/test/java/baseEntities/BaseTest.java
> +        userSteps = new UserSteps(driver, new CheckoutSteps(driver));
Для чего это?

2023-01-25 20:52 UTC, gibbonsite commented on src/test/java/baseEntities/BaseTest.java
> +        userSteps = new UserSteps(driver, new CheckoutSteps(driver));
Исправил.

2023-01-30 19:21 UTC, wildpioneer commented
Проверено

2023-01-30 19:21 UTC, closed without merging